const ACTION_TYPES = {
  // Fetching
  GET_CONTACTS_ACTION: 'GET_CONTACTS_ACTION',
  GET_CONTACTS_REQUEST: 'GET_CONTACTS_REQUEST',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CONTACTS_ERROR: 'GET_CONTACTS_ERROR',

  // Adding
  ADD_CONTACT_ACTION: 'ADD_CONTACT_ACTION',
  ADD_CONTACT_REQUEST: 'ADD_CONTACT_REQUEST',
  ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
  ADD_CONTACT_ERROR: 'ADD_CONTACT_ERROR',

  // Updating
  UPDATE_CONTACT_ACTION: 'UPDATE_CONTACT_ACTION',
  UPDATE_CONTACT_REQUEST: 'UPDATE_CONTACT_REQUEST',
  UPDATE_CONTACT_SUCCESS: 'UPDATE_CONTACT_SUCCESS',
  UPDATE_CONTACT_ERROR: 'UPDATE_CONTACT_ERROR',

  // Deleting
  DELETE_CONTACT_ACTION: 'DELETE_CONTACT_ACTION',
  DELETE_CONTACT_REQUEST: 'DELETE_CONTACT_REQUEST',
  DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
  DELETE_CONTACT_ERROR: 'DELETE_CONTACT_ERROR',

  // Синхронные экшены
  SELECT_CONTACT: 'SELECT_CONTACT',
  CLEAR_CURRENT_CONTACT: 'CLEAR_CURRENT_CONTACT',
};

export default ACTION_TYPES;